# docker-compose.yml
version: "3.8"
services:
  app:
    build: .
    # If using nvidia-container-runtime v2 or newer:
    runtime: nvidia
    environment:
      # Set your secret key here (or override in an env-file)
      - SECRET_KEY=101269
    ports:
      - "5000:5000"
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      # Mount a local nginx config to override the default
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped